### ISSUE TITLE
Include IPv4 and IPv6 support of various homeservers

### ISSUE THREAD

**Issue by erkinalp** [austinhuang0131/joinmatrix#21]

**Comment by austinhuang0131** [comment]
sure i could put it in the json but can't fit the page though

**Comment by erkinalp** [comment]
Close in favour of #60

**Comment by austinhuang0131** [comment]
added in https://codeberg.org/austinhuang/matrix-serverlist/commit/bd63d9606132204ae58b378a5f612bec7bdb07d6
