### ISSUE TITLE
mozilla.org matrix server

### ISSUE THREAD

**Issue by luca-e075e** [austinhuang0131/joinmatrix#33]
I am not able to figure out how to fill every field required to add mozilla.org matrix server.

User can register at https://chat.mozilla.org with SSO

Homeserver is **:mozilla.org**

Thanks

**Comment by austinhuang0131** [comment]
> The homeserver is [...] nor operated by Element Matrix Services (previously known as Modular).

see https://www.mozilla.org/.well-known/matrix/client, the homeserver is on modular.im
