### ISSUE TITLE
Is it your intention to have the word "nav" in the corner? 

### ISSUE THREAD

**Issue by DanilaFe** [austinhuang0131/joinmatrix#4]
Hi there! Check out this screenshot from Chrome on Android: 

![Screenshot_20211230-123724](https://user-images.githubusercontent.com/4361282/147786494-f2f6e956-c331-4325-81d0-549f020cdddc.jpg)

It looks like "nav" might have been intended to be an icon.

**Comment by austinhuang0131** [comment]
actually [it does seem to be written this way](https://github.com/pmarsceill/stately/blob/41d926e1715d77a4c14b2fed13e7fd9963a88461/_includes/_site_nav.html#L8)

i will see how i can fix it
