### ISSUE TITLE
Tor support?

### ISSUE THREAD

**Issue by zdzichu-rks** [austinhuang0131/joinmatrix#52]
Since v1.84, synapse facilitates onion<->onion federations. It's still from calling "supports", but it works, I've been successfully chatting with other hs users with full anonymity. It would be nice to add a column here for marking such support on each instance (requires a few extra steps I described here: https://github.com/matrix-org/synapse/issues/5152#issuecomment-1532280232 ).

As an example (I don't promise this instances will work long-term) I can mention two instances:
- `baleron3rtjaubsc3vtgcsyrmfmkwdyph3ui2mig7rn3mnfz5ygc4cqd.onion` (no front page, no jurisdiction, secret location, no rules, no privacy policy, in-house registration, `1.84.0` as of today)
- `matrix.privacy34kn4ez3y3nijweec6w4g54i3g54sdv7r5mr6soma3w4begyd.onion` (IDK the details)

**Comment by austinhuang0131** [comment]
The site (including the homeserver list) is intended for general (non-technical) audiences, so Tor is probably a bit too much, especially given that it's not stable/mature yet.
