### ISSUE TITLE
Server list deprecation notice

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/joinmatrix#60]
cc. @MRAAGH and @TheOneWithTheBraid

I am planning to deprecate the current server list in favour of https://servers.joinmatrix.org which is dynamic.

JSON is available at https://servers.joinmatrix.org/servers.json .

I don't have a date yet for ending the current JSON, but I am willing to accommodate, so please let me know when you are going to adapt to the new JSON.

**Comment by erkinalp** [comment]
Requested from #61 
> Show if a server supports sliding sync

**Comment by austinhuang0131** [comment]
well i did write https://gitlab.com/TheOneWithTheBraid/matrix_homeserver_recommendations/-/issues/3 honestly i'll just kill the old list like now
